export enum Role {
  ADMIN = 'ADMIN',
  PM = 'PM',
  TL = 'TL',
  USER = 'USER',
  HR = 'HR',
  FREELANCER = 'FREELANCER',
}

export enum Permission {
  // Dashboard
  DASHBOARD_OVERVIEW_VIEW = 'DASHBOARD_OVERVIEW_VIEW',
  DASHBOARD_AI_VIEW = 'DASHBOARD_AI_VIEW',
  ANALYTICS_VIEW = 'ANALYTICS_VIEW',

  // Projects
  PROJECT_LIST_VIEW = 'PROJECT_LIST_VIEW',
  PROJECT_READ = 'PROJECT_READ', // Alias/Legacy
  PROJECT_CREATE = 'PROJECT_CREATE',
  PROJECT_UPDATE = 'PROJECT_UPDATE',
  PROJECT_DELETE = 'PROJECT_DELETE',
  PROJECT_MANAGE = 'PROJECT_MANAGE',
  PROJECT_ALLOCATION_VIEW = 'PROJECT_ALLOCATION_VIEW',
  PROJECT_FUTURE_VIEW = 'PROJECT_FUTURE_VIEW',

  // Work Management
  WORK_TASK_VIEW = 'WORK_TASK_VIEW',
  WORK_TASK_UPDATE = 'WORK_TASK_UPDATE',
  WORK_TASK_IMPORT = 'WORK_TASK_IMPORT',
  WORK_SPRINT_VIEW = 'WORK_SPRINT_VIEW',
  WORK_TICKET_VIEW = 'WORK_TICKET_VIEW',

  // Workforce
  WORKFORCE_TIMESHEET_VIEW = 'WORKFORCE_TIMESHEET_VIEW',
  WORKFORCE_TIMESHEET_CREATE = 'WORKFORCE_TIMESHEET_CREATE',
  WORKFORCE_TIMESHEET_BULK_UPLOAD = 'WORKFORCE_TIMESHEET_BULK_UPLOAD',
  WORKFORCE_TIMESHEET_APPROVE = 'WORKFORCE_TIMESHEET_APPROVE',
  WORKFORCE_TEAM_TIMESHEET_VIEW = 'WORKFORCE_TEAM_TIMESHEET_VIEW',
  WORKFORCE_TIMESHEET_MISSING_VIEW = 'WORKFORCE_TIMESHEET_MISSING_VIEW',
  WORKFORCE_LEAVE_VIEW = 'WORKFORCE_LEAVE_VIEW',
  WORKFORCE_LEAVE_APPLY = 'WORKFORCE_LEAVE_APPLY',
  WORKFORCE_LEAVE_APPROVE = 'WORKFORCE_LEAVE_APPROVE',
  WORKFORCE_AVAILABILITY_VIEW = 'WORKFORCE_AVAILABILITY_VIEW',

  // Attendance
  ATTENDANCE_READ = 'ATTENDANCE_READ',
  ATTENDANCE_MARK = 'ATTENDANCE_MARK',
  ATTENDANCE_MANAGE = 'ATTENDANCE_MANAGE',
  ATTENDANCE_REGULARIZE = 'ATTENDANCE_REGULARIZE',
  ATTENDANCE_REGULARIZE_APPROVE = 'ATTENDANCE_REGULARIZE_APPROVE',

  // Comp-Off
  COMPOFF_READ = 'COMPOFF_READ',
  COMPOFF_REQUEST = 'COMPOFF_REQUEST',
  COMPOFF_APPROVE = 'COMPOFF_APPROVE',
  COMPOFF_MANAGE = 'COMPOFF_MANAGE',

  // Financial
  FINANCIAL_PO_VIEW = 'FINANCIAL_PO_VIEW',
  FINANCIAL_PO_CREATE = 'FINANCIAL_PO_CREATE',
  FINANCIAL_MILESTONE_VIEW = 'FINANCIAL_MILESTONE_VIEW',
  FINANCIAL_MILESTONE_CREATE = 'FINANCIAL_MILESTONE_CREATE',
  FINANCIAL_INVOICE_VIEW = 'FINANCIAL_INVOICE_VIEW',
  FINANCIAL_INVOICE_CREATE = 'FINANCIAL_INVOICE_CREATE',
  FINANCIAL_PAYMENT_VIEW = 'FINANCIAL_PAYMENT_VIEW',
  FINANCIAL_DASHBOARD_VIEW = 'FINANCIAL_DASHBOARD_VIEW',

  // Financial (Legacy names used in controllers)
  PO_VIEW = 'PO_VIEW',
  PO_MANAGE = 'PO_MANAGE',
  MILESTONE_VIEW = 'MILESTONE_VIEW',
  MILESTONE_MANAGE = 'MILESTONE_MANAGE',
  INVOICE_VIEW = 'INVOICE_VIEW',
  INVOICE_MANAGE = 'INVOICE_MANAGE',
  EXPENSE_VIEW = 'EXPENSE_VIEW',
  EXPENSE_MANAGE = 'EXPENSE_MANAGE',
  FINANCE_DASHBOARD = 'FINANCE_DASHBOARD',

  // Reports
  REPORT_TIMESHEET_VIEW = 'REPORT_TIMESHEET_VIEW',
  REPORT_PROJECT_VIEW = 'REPORT_PROJECT_VIEW',
  REPORT_UTILIZATION_VIEW = 'REPORT_UTILIZATION_VIEW',
  REPORT_ALL_VIEW = 'REPORT_ALL_VIEW',
  // Already seeded (seed-role-permissions-only.ts) but missing from this enum
  // until now — added alongside the two new report permissions below.
  REPORT_LEAVE_VIEW = 'REPORT_LEAVE_VIEW',
  REPORT_ATTENDANCE_VIEW = 'REPORT_ATTENDANCE_VIEW',
  REPORT_TIMESHEET_DETAILED_VIEW = 'REPORT_TIMESHEET_DETAILED_VIEW',
  REPORT_TIMESHEET_DETAILED_EXPORT = 'REPORT_TIMESHEET_DETAILED_EXPORT',
  REPORT_MONTHLY_EFFORTS_VIEW = 'REPORT_MONTHLY_EFFORTS_VIEW',
  REPORT_MONTHLY_ATTENDANCE_VIEW = 'REPORT_MONTHLY_ATTENDANCE_VIEW',
  REPORT_NON_COMPLIANCE_VIEW = 'REPORT_NON_COMPLIANCE_VIEW',

  // Task Type Master
  TASK_TYPE_MASTER_VIEW = 'TASK_TYPE_MASTER_VIEW',
  TASK_TYPE_MASTER_MANAGE = 'TASK_TYPE_MASTER_MANAGE',

  // Employee Maturity
  MATURITY_VIEW = 'MATURITY_VIEW',
  MATURITY_MANAGE = 'MATURITY_MANAGE',

  // Todo List / Activities
  ACTIVITY_VIEW = 'ACTIVITY_VIEW',
  ACTIVITY_CREATE = 'ACTIVITY_CREATE',
  ACTIVITY_MANAGE = 'ACTIVITY_MANAGE',

  // Administration
  ADMIN_USER_VIEW = 'ADMIN_USER_VIEW',
  ADMIN_ROLE_VIEW = 'ADMIN_ROLE_VIEW',
  ADMIN_MENU_VIEW = 'ADMIN_MENU_VIEW',
  MENU_READ = 'MENU_READ',
  MENU_CREATE = 'MENU_CREATE',
  MENU_UPDATE = 'MENU_UPDATE',

  MENU_DELETE = 'MENU_DELETE',
  ADMIN_HOLIDAY_VIEW = 'ADMIN_HOLIDAY_VIEW',
  ADMIN_SKILL_VIEW = 'ADMIN_SKILL_VIEW',
  ADMIN_RA_VIEW = 'ADMIN_RA_VIEW',
  ADMIN_CONFIG_VIEW = 'ADMIN_CONFIG_VIEW',
  ADMIN_CONFIG_EDIT = 'ADMIN_CONFIG_EDIT',

  // Demands
  DEMAND_VIEW = 'DEMAND_VIEW',
  DEMAND_CREATE = 'DEMAND_CREATE',
  DEMAND_APPROVE = 'DEMAND_APPROVE',
  DEMAND_CONVERT = 'DEMAND_CONVERT',

  // Training
  TRAINING_READ = 'TRAINING_READ',
  TRAINING_MANAGE = 'TRAINING_MANAGE',
  TRAINING_ENROLL = 'TRAINING_ENROLL',

  // Testing
  TEST_READ = 'TEST_READ',
  TEST_MANAGE = 'TEST_MANAGE',
  TEST_EXECUTE = 'TEST_EXECUTE',

  // Tracker
  TRACKER_VIEW = 'TRACKER_VIEW',
  TRACKER_EXPORT = 'TRACKER_EXPORT',

  // Users
  USER_READ = 'USER_READ',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_MANAGE = 'USER_MANAGE',
}
